#!/usr/bin/env bash
readonly command="$(basename "${0}")"
subcommand="$(echo "${command}" | cut -s -d. -f2)"

case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)
  OS="OSX"
  echo $OS ;; 
  linux*)
  OS="Linux"
  echo $OS ;;
  msys*)
  OS="Windows"
  echo $OS ;;
  *)        echo "unknown: $OSTYPE" ;;
esac

if [[ "${subcommand}" == "" ]]; then
    subcommand="${1}"
fi

if [[ "${subcommand}" == "" ]]; then
    echo "Error: Command not found" 1>&2
    exit 1
fi

if [[ "${subcommand}" == "open" ]]; then
    echo "Open Start" 1>&2
    if [[ "$OS" == "OSX" ]]; then
    ETICON_PATH=$(which eticon)
    open -n "${ETICON_PATH}_core.app" --args "$PWD"
fi
    exit 1
fi

echo "Eticon Error: Command not found" 2>&1 &
exit 1